# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\KTLT\Module2\C27PhanMemToiUuChuoiDanhTu\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 335)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 711, 231))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background: rgb(249, 247, 247);\n"
"color: rgb(63, 114, 175);\n"
"border-radius: 7px;\n"
"border: 0.7px solid black;")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius: 0px;\n"
"border: 0px;")
        self.label_2.setObjectName("label_2")
        self.lineEditInput = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditInput.setGeometry(QtCore.QRect(140, 40, 551, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(11)
        self.lineEditInput.setFont(font)
        self.lineEditInput.setStyleSheet("background: rgb(219, 226, 239);\n"
"color: rgb(17, 45, 78);\n"
"border-radius: 10px;")
        self.lineEditInput.setObjectName("lineEditInput")
        self.lineEditOutput = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditOutput.setEnabled(False)
        self.lineEditOutput.setGeometry(QtCore.QRect(140, 100, 551, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(11)
        self.lineEditOutput.setFont(font)
        self.lineEditOutput.setStyleSheet("background: rgb(219, 226, 239);\n"
"color: rgb(17, 45, 78);\n"
"border-radius: 10px;")
        self.lineEditOutput.setObjectName("lineEditOutput")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 91, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 0px;\n"
"border: 0px;")
        self.label_3.setObjectName("label_3")
        self.pushButtonOptimize = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonOptimize.setGeometry(QtCore.QRect(90, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonOptimize.setFont(font)
        self.pushButtonOptimize.setStyleSheet("background: rgb(219, 226, 239);\n"
"color: rgb(17, 45, 78);\n"
"border-radius: 15px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Dung Lam\\PycharmProjects\\KTLT\\Module2\\C27PhanMemToiUuChuoiDanhTu\\ui\\../images/ic_convert.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOptimize.setIcon(icon)
        self.pushButtonOptimize.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonOptimize.setObjectName("pushButtonOptimize")
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonNew.setGeometry(QtCore.QRect(280, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonNew.setFont(font)
        self.pushButtonNew.setStyleSheet("background: rgb(219, 226, 239);\n"
"color: rgb(17, 45, 78);\n"
"border-radius: 15px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Dung Lam\\PycharmProjects\\KTLT\\Module2\\C27PhanMemToiUuChuoiDanhTu\\ui\\../images/ic_new.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNew.setIcon(icon1)
        self.pushButtonNew.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonExit.setGeometry(QtCore.QRect(470, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("background: rgb(219, 226, 239);\n"
"color: rgb(17, 45, 78);\n"
"border-radius: 15px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Dung Lam\\PycharmProjects\\KTLT\\Module2\\C27PhanMemToiUuChuoiDanhTu\\ui\\../images/ic_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon2)
        self.pushButtonExit.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Optimize Noun Application:"))
        self.label_2.setText(_translate("MainWindow", "Input string:"))
        self.label_3.setText(_translate("MainWindow", "Result:"))
        self.pushButtonOptimize.setText(_translate("MainWindow", "Optimize"))
        self.pushButtonNew.setText(_translate("MainWindow", "New"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
