# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\KTLT\PrintPerfectNumber\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 248)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 391, 171))
        self.groupBox.setStyleSheet("background: rgb(221, 255, 211);")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 40, 71, 31))
        self.label.setObjectName("label")
        self.lineEditN = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditN.setGeometry(QtCore.QRect(110, 50, 211, 20))
        self.lineEditN.setStyleSheet("background: rgb(215, 237, 255)")
        self.lineEditN.setObjectName("lineEditN")
        self.pushButtonPrint = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonPrint.setGeometry(QtCore.QRect(50, 90, 71, 31))
        self.pushButtonPrint.setStyleSheet("background: rgb(215, 237, 255)")
        self.pushButtonPrint.setObjectName("pushButtonPrint")
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonNew.setGeometry(QtCore.QRect(150, 90, 71, 31))
        self.pushButtonNew.setStyleSheet("background: rgb(215, 237, 255)")
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonExit.setGeometry(QtCore.QRect(250, 90, 71, 31))
        self.pushButtonExit.setStyleSheet("background: rgb(215, 237, 255)")
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Print Perfect Numbers:"))
        self.label.setText(_translate("MainWindow", "Input N:"))
        self.pushButtonPrint.setText(_translate("MainWindow", "Print"))
        self.pushButtonNew.setText(_translate("MainWindow", "New"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
