# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\KTLT\PrintPerfectNumber\ResultWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 331)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 391, 231))
        self.groupBox.setStyleSheet("background: rgb(221, 255, 211);")
        self.groupBox.setObjectName("groupBox")
        self.lineEditPerfectNumbers = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPerfectNumbers.setEnabled(False)
        self.lineEditPerfectNumbers.setGeometry(QtCore.QRect(40, 40, 311, 161))
        self.lineEditPerfectNumbers.setStyleSheet("background: rgb(215, 237, 255)")
        self.lineEditPerfectNumbers.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditPerfectNumbers.setObjectName("lineEditPerfectNumbers")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Perfect numbers from 1 to N (include N):"))
