# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\ATM\final\ATMMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from final.CustomerChoice import Ui_CustomerChoice_2


class Ui_MainWindow(object):
    def open_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CustomerChoice_2()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 618)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 30, 381, 541))
        self.widget.setStyleSheet("background-color: rgba(121,209,137,0.8);\n"
"border-radius: 15px;")
        self.widget.setObjectName("widget")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEditName.setGeometry(QtCore.QRect(20, 230, 331, 61))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditName.setFont(font)
        self.lineEditName.setStyleSheet("background-color: rgba(211,231,214,0.8);\n"
"")
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEditPassword.setGeometry(QtCore.QRect(20, 350, 331, 61))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("background-color: rgba(211,231,214,0.8);\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonLogin.clicked.connect(self.open_window)
        self.pushButtonLogin.setGeometry(QtCore.QRect(120, 460, 131, 41))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("QPushButton#pushButtonLogin{\n"
"        background-color: rgba(60,81,43,0.6);\n"
"        color: rgba(255,255,255,0.7);\n"
"        border-radius: 10px;}\n"
"QPushButton#pushButtonLogin::pressed{\n"
"        padding-left: 5px;\n"
"        padding-top:5px;\n"
"        background-color: rgba(136,172,107,0.6);\n"
"}\n"
"QQPushButton#pushButtonLogin::hover{\n"
"        background-color: rgba(136,172,107,0.4);\n"
"}")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(110, 40, 151, 151))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(100)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: rgba(26,35,18,0.8);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.textoutput_ledName = QtWidgets.QTextBrowser(parent=self.widget)
        self.textoutput_ledName.setGeometry(QtCore.QRect(20, 300, 331, 31))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        self.textoutput_ledName.setFont(font)
        self.textoutput_ledName.setStyleSheet("background-color: rgba(255,255,255,0);")
        self.textoutput_ledName.setObjectName("textoutput_ledName")
        self.textoutput_ledPass = QtWidgets.QTextBrowser(parent=self.widget)
        self.textoutput_ledPass.setGeometry(QtCore.QRect(20, 420, 331, 31))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        self.textoutput_ledPass.setFont(font)
        self.textoutput_ledPass.setStyleSheet("background-color: rgba(255,255,255,0);")
        self.textoutput_ledPass.setObjectName("textoutput_ledPass")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditName.setPlaceholderText(_translate("MainWindow", "  Tên tài khoản: "))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "  Mật khẩu: "))
        self.pushButtonLogin.setText(_translate("MainWindow", "L o g i n"))
        self.label.setText(_translate("MainWindow", ""))
