# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\ATM\final\CustomerChoice.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomerChoice_2(object):
    def setupUi(self, CustomerChoice_2):
        CustomerChoice_2.setObjectName("CustomerChoice_2")
        CustomerChoice_2.resize(669, 671)
        self.centralwidget = QtWidgets.QWidget(parent=CustomerChoice_2)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 40, 381, 411))
        self.widget.setStyleSheet("background-color: rgba(121,209,137,0.8);\n"
"border-radius: 15px;")
        self.widget.setObjectName("widget")
        self.labelquestion = QtWidgets.QLabel(parent=self.widget)
        self.labelquestion.setGeometry(QtCore.QRect(30, 40, 341, 51))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelquestion.setFont(font)
        self.labelquestion.setStyleSheet("background-color: rgba(255,255,255,0);")
        self.labelquestion.setObjectName("labelquestion")
        self.pushButtonTracuu = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonTracuu.setGeometry(QtCore.QRect(120, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTracuu.setFont(font)
        self.pushButtonTracuu.setStyleSheet("QPushButton#pushButtonLogin{\n"
"        background-color: rgba(60,81,43,0.6);\n"
"        color: rgba(255,255,255,0.7);\n"
"        border-radius: 10px;}\n"
"QPushButton#pushButtonLogin::pressed{\n"
"        padding-left: 5px;\n"
"        padding-top:5px;\n"
"        background-color: rgba(136,172,107,0.6);\n"
"}\n"
"QQPushButton#pushButtonLogin::hover{\n"
"        background-color: rgba(136,172,107,0.4);\n"
"}")
        self.pushButtonTracuu.setObjectName("pushButtonTracuu")
        self.pushButtonRuttien = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonRuttien.setGeometry(QtCore.QRect(120, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRuttien.setFont(font)
        self.pushButtonRuttien.setStyleSheet("QPushButton#pushButtonLogin{\n"
"        background-color: rgba(60,81,43,0.6);\n"
"        color: rgba(255,255,255,0.7);\n"
"        border-radius: 10px;}\n"
"QPushButton#pushButtonLogin::pressed{\n"
"        padding-left: 5px;\n"
"        padding-top:5px;\n"
"        background-color: rgba(136,172,107,0.6);\n"
"}\n"
"QQPushButton#pushButtonLogin::hover{\n"
"        background-color: rgba(136,172,107,0.4);\n"
"}")
        self.pushButtonRuttien.setObjectName("pushButtonRuttien")
        self.pushButtonChuyentien = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonChuyentien.setGeometry(QtCore.QRect(120, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonChuyentien.setFont(font)
        self.pushButtonChuyentien.setStyleSheet("QPushButton#pushButtonLogin{\n"
"        background-color: rgba(60,81,43,0.6);\n"
"        color: rgba(255,255,255,0.7);\n"
"        border-radius: 10px;}\n"
"QPushButton#pushButtonLogin::pressed{\n"
"        padding-left: 5px;\n"
"        padding-top:5px;\n"
"        background-color: rgba(136,172,107,0.6);\n"
"}\n"
"QQPushButton#pushButtonLogin::hover{\n"
"        background-color: rgba(136,172,107,0.4);\n"
"}")
        self.pushButtonChuyentien.setObjectName("pushButtonChuyentien")
        self.pushButtonDoimk = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonDoimk.setGeometry(QtCore.QRect(120, 340, 131, 41))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDoimk.setFont(font)
        self.pushButtonDoimk.setStyleSheet("QPushButton#pushButtonLogin{\n"
"        background-color: rgba(60,81,43,0.6);\n"
"        color: rgba(255,255,255,0.7);\n"
"        border-radius: 10px;}\n"
"QPushButton#pushButtonLogin::pressed{\n"
"        padding-left: 5px;\n"
"        padding-top:5px;\n"
"        background-color: rgba(136,172,107,0.6);\n"
"}\n"
"QQPushButton#pushButtonLogin::hover{\n"
"        background-color: rgba(136,172,107,0.4);\n"
"}")
        self.pushButtonDoimk.setObjectName("pushButtonDoimk")
        self.pushButtonThoat = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonThoat.setGeometry(QtCore.QRect(120, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("SVN-HC 1785 GLC Baskerville")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonThoat.setFont(font)
        self.pushButtonThoat.setStyleSheet("QPushButton#pushButtonLogin{\n"
"        background-color: rgba(60,81,43,0.59);\n"
"        color: rgba(255,255,255,0.7);\n"
"        border-radius: 10px;}\n"
"QPushButton#pushButtonLogin::pressed{\n"
"        padding-left: 5px;\n"
"        padding-top:5px;\n"
"        background-color: rgba(136,172,107,0.6);\n"
"}\n"
"QQPushButton#pushButtonLogin::hover{\n"
"        background-color: rgba(136,172,107,0.4);\n"
"}")
        self.pushButtonThoat.setObjectName("pushButtonThoat")
        CustomerChoice_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CustomerChoice_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 669, 25))
        self.menubar.setObjectName("menubar")
        CustomerChoice_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CustomerChoice_2)
        self.statusbar.setObjectName("statusbar")
        CustomerChoice_2.setStatusBar(self.statusbar)

        self.retranslateUi(CustomerChoice_2)
        QtCore.QMetaObject.connectSlotsByName(CustomerChoice_2)

    def retranslateUi(self, CustomerChoice_2):
        _translate = QtCore.QCoreApplication.translate
        CustomerChoice_2.setWindowTitle(_translate("CustomerChoice_2", "MainWindow"))
        self.labelquestion.setText(_translate("CustomerChoice_2", "Bạn muốn dùng tính năng nào sau đây?"))
        self.pushButtonTracuu.setText(_translate("CustomerChoice_2", "Tra cứu số dư"))
        self.pushButtonRuttien.setText(_translate("CustomerChoice_2", "Rút tiền"))
        self.pushButtonChuyentien.setText(_translate("CustomerChoice_2", "Chuyển tiền"))
        self.pushButtonDoimk.setText(_translate("CustomerChoice_2", "Đổi mật khẩu"))
        self.pushButtonThoat.setText(_translate("CustomerChoice_2", "Thoát"))
