# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\KTLT\Module2\C39InteractwithListApp\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 562)
        MainWindow.setStyleSheet("background: rgb(248, 250, 252);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 31, 16))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditNumber.setGeometry(QtCore.QRect(80, 70, 211, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.lineEditNumber.setFont(font)
        self.lineEditNumber.setStyleSheet("background: rgb(217, 234, 253);\n"
"border-radius: 10px;\n"
"border: 0.5px solid black;")
        self.lineEditNumber.setObjectName("lineEditNumber")
        self.pushButtonCreateRandom = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCreateRandom.setGeometry(QtCore.QRect(320, 70, 121, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonCreateRandom.setFont(font)
        self.pushButtonCreateRandom.setStyleSheet("background: rgb(217, 234, 253);\n"
"border-radius: 10px;\n"
"border: 0.5px solid black;\n"
"")
        self.pushButtonCreateRandom.setObjectName("pushButtonCreateRandom")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(50, 120, 241, 361))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("background: rgb(188, 204, 220);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 239, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutButtons = QtWidgets.QVBoxLayout()
        self.verticalLayoutButtons.setObjectName("verticalLayoutButtons")
        self.verticalLayout_2.addLayout(self.verticalLayoutButtons)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAdd.setGeometry(QtCore.QRect(320, 130, 121, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonAdd.setFont(font)
        self.pushButtonAdd.setStyleSheet("background: rgb(217, 234, 253);\n"
"border-radius: 10px;\n"
"border: 0.5px solid black;\n"
"")
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonUpdate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(320, 190, 121, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setStyleSheet("background: rgb(217, 234, 253);\n"
"border-radius: 10px;\n"
"border: 0.5px solid black;\n"
"")
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDelete.setGeometry(QtCore.QRect(320, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setStyleSheet("background: rgb(217, 234, 253);\n"
"border-radius: 10px;\n"
"border: 0.5px solid black;\n"
"")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonAscSort = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAscSort.setGeometry(QtCore.QRect(320, 310, 121, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonAscSort.setFont(font)
        self.pushButtonAscSort.setStyleSheet("background: rgb(217, 234, 253);\n"
"border-radius: 10px;\n"
"border: 0.5px solid black;\n"
"")
        self.pushButtonAscSort.setObjectName("pushButtonAscSort")
        self.pushButtonRemoveAll = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRemoveAll.setGeometry(QtCore.QRect(320, 430, 121, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonRemoveAll.setFont(font)
        self.pushButtonRemoveAll.setStyleSheet("background: rgb(217, 234, 253);\n"
"border-radius: 10px;\n"
"border: 0.5px solid black;\n"
"")
        self.pushButtonRemoveAll.setObjectName("pushButtonRemoveAll")
        self.pushButtonDescSort = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDescSort.setGeometry(QtCore.QRect(320, 370, 121, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Arima Madurai ExtraBo")
        font.setPointSize(10)
        self.pushButtonDescSort.setFont(font)
        self.pushButtonDescSort.setStyleSheet("background: rgb(217, 234, 253);\n"
"border-radius: 10px;\n"
"border: 0.5px solid black;\n"
"")
        self.pushButtonDescSort.setObjectName("pushButtonDescSort")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lâm Thuỳ Dung"))
        self.label.setText(_translate("MainWindow", "List Operation"))
        self.label_2.setText(_translate("MainWindow", "N:"))
        self.lineEditNumber.setText(_translate("MainWindow", "50"))
        self.pushButtonCreateRandom.setText(_translate("MainWindow", "Create Random"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
        self.pushButtonAscSort.setText(_translate("MainWindow", "Asc Sort"))
        self.pushButtonRemoveAll.setText(_translate("MainWindow", "Remove All"))
        self.pushButtonDescSort.setText(_translate("MainWindow", "Desc Sort"))
